# Generated by Django 4.2.13 on 2024-05-27 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_app', '0002_region_sales_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='sales_amount',
        ),
    ]
